name: Rebuild and deploy

on:
  # Trigger the workflow on a push to the main branch
  push:
    branches:
      - main
  # Trigger manuale
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Rebuild and deploy

    steps:
      - name: Rebuild and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_DIRECTION }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd ~/blog && git fetch origin && git reset --hard origin/main && docker compose down -v && docker compose up --build -d